---
- hosts: 127.0.0.1
  connection: local

  vars:
    dev_env_dir: /usr/local/gdev-env/

  tasks:

    - name: Check Sudo Password
      command: ls
      become: yes
      become_method: sudo

    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: Install Docker and Extras
      homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - docker
        - docker-compose
        - dlite

    - name: Start dlite
      command: "{{ dev_env_dir }}/bin/dev machine create"
      args:
        creates: "/Users/onnimonni/.dlite/config.json"

    - name: Get dlite ip address
      shell: /usr/local/bin/dlite ip
      register: machine_ip

    - name: "Debug dlite ip"
      debug:
        msg: "Dlite is up and running: {{ machine_ip.stdout }}"

    - name: Create resolver directory
      file: path=/etc/resolver state=directory mode=0755
      become: yes
      become_method: sudo

    - name: Create dns resolver files at /etc/resolver/
      template:
        src: "{{ dev_env_dir }}/ansible/resolver-dev.conf.j2"
        dest: "/etc/resolver/{{item.domain}}"
        force: yes
      become: yes
      become_method: sudo
      with_items:
        - { ip: "{{ machine_ip.stdout }}", domain: test }

    - name: Add dev binary to PATH to .zshrc
      lineinfile:
        dest: ~/.zshrc
        line: "source {{ dev_env_dir }}/ansible/mac_profile"
        create: yes
      when: ansible_env.SHELL == "/bin/zsh" or ansible_env.SHELL == "/usr/local/bin/zsh"

    - name: Add dev binary to PATH to .bash_profile
      lineinfile:
        dest: ~/.bash_profile
        line: "source {{ dev_env_dir }}/ansible/mac_profile"
        create: yes
      when: ansible_env.SHELL == "/bin/bash"

    - name: Add dev binary to PATH to .config/fish/config.fish
      lineinfile:
        dest: ~/.config/fish/config.fish
        line: "source {{ dev_env_dir }}/ansible/mac_profile.fish"
        create: yes
      when: ansible_env.SHELL == "/usr/local/bin/fish"