---
- hosts: 127.0.0.1
  connection: local

  vars:
    dev_env_dir: /usr/local/gdev-env

  tasks:

    - name: Check Sudo Password
      command: ls
      become: yes
      become_method: sudo

    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: Install Docker and Extras
      homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - docker
        - docker-compose
        - dlite

    - name: Create dlite directory
      file:
        path: "{{ansible_env.HOME}}/.dlite"
        state: directory
        mode: 0755

    - name: Create gdev directory
      file:
        path: "{{ansible_env.HOME}}/.gdev"
        state: directory
        mode: 0755

    - name: Symlink gdev bin to PATH
      file:
        src: /usr/local/gdev-env/bin/gdev
        dest: /usr/local/bin/gdev

    - name: Start dlite
      command: "{{ dev_env_dir }}/bin/gdev machine create"
      args:
        creates: "{{ansible_env.HOME}}/.dlite/config.json"
      become: yes
      become_method: sudo

    - name: Get dlite ip address
      shell: /usr/local/bin/dlite ip
      register: machine_ip

    - name: "Debug dlite ip"
      debug:
        msg: "Dlite is up and running: {{ machine_ip.stdout }}"

    - name: Create resolver directory
      file: path=/etc/resolver state=directory mode=0755
      become: yes
      become_method: sudo

    - name: Delete resolver files to trigger dns change
      file:
        path: "/etc/resolver/{{item.domain}}"
        state: absent
      become: yes
      become_method: sudo
      with_items:
        - { ip: "{{ machine_ip.stdout }}", domain: test }

    - name: Create dns resolver files at /etc/resolver/
      template:
        src: "{{ dev_env_dir }}/ansible/resolver-dev.conf.j2"
        dest: "/etc/resolver/{{item.domain}}"
        force: yes
      become: yes
      become_method: sudo
      with_items:
        - { ip: "{{ machine_ip.stdout }}", domain: test }
