---
- hosts: 127.0.0.1
  connection: local

  vars:
    gdev_env_dir: "/usr/local/gdev-env"
    gdev_user_files: "{{ansible_env.HOME}}/.gdev"
    machine_ip: 127.0.0.1

  tasks:
    - name: Give sudo password some time to load correctly
      pause: seconds=5
    
    - name: Make sure apt-transport-https is installed
      become: yes
      become_method: sudo
      apt:
        pkg: "apt-transport-https"
        state: installed

    - name: Add Docker repository key
      become: yes
      become_method: sudo
      apt_key: id=58118E89F3A912897C070ADBF76221572C52609D keyserver=hkp://p80.pool.sks-keyservers.net:80 state=present

    - name: Add Docker repository and update apt cache
      become: yes
      become_method: sudo
      apt_repository:
        repo: "deb http://get.docker.io/ubuntu docker main"
        update_cache: yes
        state: present

    - name: Install lxc-docker
      become: yes
      become_method: sudo
      apt: pkg=lxc-docker state=installed install_recommends=yes allow_unauthenticated=yes
    
    - name: Install Unison
      homebrew: name=unison state=present

    - name: Install Docker-py
      become: yes
      become_method: sudo
      pip:
        name: docker-py
        
    - name: Installing docker compose
      become: yes
      become_method: sudo
      pip:
        name: docker-compose
        state: present
      

    - name: Create gdev directory
      file:
        path: "{{ansible_env.HOME}}/.gdev"
        state: directory
        owner: "{{ansible_env.USER}}"
        group: "staff"
        recurse: yes
        mode: 0755
      # If this was somehow root owned make sure it's not anymore
      become: yes
      become_method: sudo

    - name: Symlink gdev bin to PATH
      become: yes
      become_method: sudo
      file:
        src: "{{gdev_env_dir}}/bin/gdev"
        dest: /usr/local/bin/gdev
        state: link
        force: yes
      tags: ['pre-install']
      
    - name: Adding user to docker group
      user: 
        name: "{{ansible_env.USER}}"
        groups: docker
        append: yes

    - name: Make sure docker is running
      become: yes
      become_method: sudo
      service:
        name: docker
        state: started


    - name: "Check that we have /var/run/docker.sock socket"
      wait_for:
        path: /var/run/docker.sock
        state: present
        timeout: 20

    - name: "Check that we have /var/run/docker.sock socket"
      stat: path=/var/run/docker.sock
      register: docker_socket

    - name: Fail if no docker.sock
      fail: msg="Check that docker is enabled! /var/run/docker.sock is not mounted :(..."
      when: not docker_socket.stat.exists

    - name: Start gdev services
      command: "{{ gdev_env_dir }}/bin/gdev service up"

    - name: Wait for signaler to create CA file
      wait_for:
        path: "{{ gdev_user_files }}/ca/ca.crt"
        state: present
        timeout: 30

    # We want to use https locally and you only use ca.key which is generated to you
    - name: Trust self-generated signaler Root certificate in keychain
      shell: "cp ca.crt /usr/local/share/ca-certificates/ && sudo update-ca-certificates"
      args:
        chdir: "{{ gdev_user_files }}/ca/"
      become: yes
      become_method: sudo

    - name: Create dns resolver files at /etc/NetworkManager/dnsmasq.d/
      template:
        src: "{{ gdev_env_dir }}/ansible/nm-dnsmasq-dev.conf.j2"
        dest: "/etc/NetworkManager/dnsmasq.d/{{item.domain}}"
        force: yes
      become: yes
      become_method: sudo
      with_items:
        - { ip: "{{ machine_ip }}", domain: test }

    - name: Restart network-manager
      service: 
        name: network-manager
        state: restarted
      become: yes
      become_method: sudo
